name: flutter_mobile_ppks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.6+10

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  # ===== FIREBASE (OPSIONAL / BACKUP DATA) =====
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.7.7

  # ===== AUTH & NETWORK =====
  google_sign_in: ^6.2.1
  http: ^1.2.0
  crypto: ^3.0.3

  # ===== LOCAL STORAGE (ANDROID + WEB) =====
  shared_preferences: ^2.2.3

  # ===== FILE & MEDIA =====
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  share_plus: ^7.2.1

  # ===== DATABASE (OPSIONAL, BELUM DIPAKAI) =====
  sqflite: ^2.3.0
  path: ^1.8.3 
  sqflite_common_ffi: ^2.2.0

  # ===== FORMAT & UI =====
  intl: ^0.18.1
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.8

  # ===== ABSENSI (KAMERA & VERIFIKASI WAJAH) =====
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.10.0
  image: ^4.2.0

  # ===== ABSENSI (TRACKING LOKASI LATAR BELAKANG) =====
  flutter_foreground_task: ^8.17.0
  permission_handler: ^11.3.1

  # ===== ABSENSI (LINK UNDANGAN / DEEP LINK) =====
  app_links: ^7.0.0

  # ===== ABSENSI (LOKASI GPS SAAT ABSEN) =====
  geolocator: 12.0.0
  url_launcher: ^6.3.1
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/download (3).jpg
    - assets/images/Me.jpg
    - assets/images/google.jpg