// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lFpbKT5rh3BS1SVHTktNoqSJjpfxkTQ',
    appId: '1:627205299434:web:ef339cad9643bc61c4cb93',
    messagingSenderId: '627205299434',
    projectId: 'mobile-android-a7432',
    authDomain: 'mobile-android-a7432.firebaseapp.com',
    storageBucket: 'mobile-android-a7432.firebasestorage.app',
    measurementId: 'G-TBP2J2J29F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMi5bNHByAvE4nam_LysNaggyoLcLQaDM',
    appId: '1:627205299434:android:9a495dd244f3f0f3c4cb93',
    messagingSenderId: '627205299434',
    projectId: 'mobile-android-a7432',
    storageBucket: 'mobile-android-a7432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBas1xvJJmPBOm0EUOHzhpD_rMdQmGpGqA',
    appId: '1:166549220113:ios:bb0e5d9fcdb5ef7c7bbab0',
    messagingSenderId: '166549220113',
    projectId: 'kawal-kebun',
    storageBucket: 'kawal-kebun.firebasestorage.app',
    iosBundleId: 'com.ppks.kawalkebun',
    iosClientId: '166549220113-sukag87bqc9cmanppbjusqnttpk5l8tb.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBas1xvJJmPBOm0EUOHzhpD_rMdQmGpGqA',
    appId: '1:166549220113:ios:bb0e5d9fcdb5ef7c7bbab0',
    messagingSenderId: '166549220113',
    projectId: 'kawal-kebun',
    storageBucket: 'kawal-kebun.firebasestorage.app',
    iosBundleId: 'com.ppks.kawalkebun',
    iosClientId: '166549220113-sukag87bqc9cmanppbjusqnttpk5l8tb.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPUJQcG6d5ayC6rc5tMAWn6UUbiEC66zI',
    appId: '1:1050782929738:web:1770a894e6df8ed4fba7b3',
    messagingSenderId: '1050782929738',
    projectId: 'fluttermobile-77956',
    authDomain: 'fluttermobile-77956.firebaseapp.com',
    storageBucket: 'fluttermobile-77956.firebasestorage.app',
    measurementId: 'G-KTQW1GTN22',
  );

}